ports:
  - port: 8000
    onOpen: open-preview
    name: Demo
    description: Preview
    
tasks:
  - name: Setup dependencies and run app
    init: |
      poetry export -f requirements.txt --output requirements.gitpod --without-hashes
      echo 'CSRF_TRUSTED_ORIGINS = ["https://*.gitpod.io"]' >> tests/gitpod_settings.py
      pre-commit install
    command: |
      pip install -U pip
      pip install -r requirements.gitpod
      python3 manage.py migrate
      echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'admin')" | python3 manage.py shell
      python3 manage.py runserver 0.0.0.0:8000
