repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.10
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.39
    hooks:
      - id: pymarkdown
        args:
          - --disable-rules
          - line-length
          - scan
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.32.0"  # replace with latest tag on GitHub
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.2"]   # Replace with Django version
