[tox]
skipsdist = True
usedevelop = True
isolated_build = True

envlist = 
    py{310,311,312}-django42-wagtail{63,70,71,72,73}-sqlite
    py{312,313}-django{51,52}-wagtail{70,71,72}-sqlite
    py{312,313}-django{52,60}-wagtail73-sqlite
    py314-django60-wagtail73-sqlite
    py{310,311}-django52-wagtail74-sqlite
    py{312,313,314}-django{52,60}-wagtail74-sqlite
    py314-django60-wagtail74-{postgres,mysql}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[gh-actions:env]
DATABASE = 
    sqlite: sqlite
    postgres: postgres
    mysql: mysql

[testenv]
skip_install = True
commands = 
    coverage run manage.py test --deprecation all
    coverage report

deps =
    coverage

    django42: Django>=4.2,<5.0
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1

    wagtail63: wagtail>=6.3,<6.4
    wagtail70: wagtail>=7.0,<7.1
    wagtail71: wagtail>=7.1,<7.2
    wagtail72: wagtail>=7.2,<7.3
    wagtail73: wagtail>=7.3,<7.4
    wagtail74: wagtail>=7.4,<7.5

    postgres: psycopg2
    mysql: mysqlclient
