# Generated by Django 4.0.7 on 2022-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="honeypot",
            field=models.BooleanField(default=False, verbose_name="Honeypot Enabled"),
        ),
    ]
